# Generated by Django 4.1.5 on 2023-01-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.FloatField()),
                ('std', models.FloatField()),
                ('val', models.FloatField()),
                ('z', models.FloatField()),
            ],
        ),
    ]
